//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerCenter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CenterModelContainer : DbContext
    {
        public CenterModelContainer()
            : base("name=CenterModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaudRateModel> BaudRateModel { get; set; }
        public DbSet<CodedFormatModel> CodedFormatModel { get; set; }
        public DbSet<CommPortModel> CommPortModel { get; set; }
        public DbSet<CommunicationModeModel> CommunicationModeModel { get; set; }
        public DbSet<DataBitModel> DataBitModel { get; set; }
        public DbSet<DeviceActionModel> DeviceActionModel { get; set; }
        public DbSet<DeviceModel> DeviceModel { get; set; }
        public DbSet<InteractiveAreaModel> InteractiveAreaModel { get; set; }
        public DbSet<IpConfigModel> IpConfigModel { get; set; }
        public DbSet<IpModel> IpModel { get; set; }
        public DbSet<OperateConfigModel> OperateConfigModel { get; set; }
        public DbSet<ParityCheckBitModel> ParityCheckBitModel { get; set; }
        public DbSet<SerialPortConfigModel> SerialPortConfigModel { get; set; }
        public DbSet<StopBitModel> StopBitModel { get; set; }
    }
}
