//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialPortConfigModel
    {
        public int Id { get; set; }
        public int CommPortId { get; set; }
        public int BaudRateId { get; set; }
        public int DataBitId { get; set; }
        public int StopBitId { get; set; }
        public int ParityCheckBitId { get; set; }
    }
}
